export const FETCH_MY_LIST = "FETCH_MY_LIST";
export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
export const ADD_MOVIE = "ADD_MOVIE";
export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const ADD_RECOMMENDATION = "ADD_RECOMMENDATION";
export const REMOVE_RECOMMENDATION = "REMOVE_RECOMMENDATION";
